repos:
    -   hooks:
            -   always_run: true
                entry: .hooks/branch
                id: branch-naming
                language: script
                name: Branch naming convention check
                stages:
                    - pre-commit
        repo: local
    -   hooks:
            -   id: check-ast
                language_version: python3.13
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   exclude: ^k8s/
                id: check-yaml
            -   id: check-toml
            -   args:
                    - --branch
                    - main
                    - --branch
                    - master
                id: no-commit-to-branch
        repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
    -   hooks:
            -   id: add-trailing-comma
        repo: https://github.com/asottile/add-trailing-comma
        rev: v3.2.0
    -   hooks:
            -   args:
                    - --py313-plus
                id: pyupgrade
        repo: https://github.com/asottile/pyupgrade
        rev: v3.20.0
    -   hooks:
            -   entry: uv run ruff format
                id: format
                language: system
                name: format
                require_serial: true
                types:
                    - python
        repo: local
    -   hooks:
            -   entry: uv run ruff check
                id: lint
                language: system
                name: lint
                require_serial: true
                types:
                    - python
        repo: local
    -   hooks:
            -   id: mypy
        repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.18.2
        args:

    -   hooks:
            -   entry: uv run basedpyright
                id: pyright
                language: system
                name: pyright
                types:
                    - python
        repo: local
    -   hooks:
            -   id: ggshield
                language_version: python3
                stages:
                    - pre-commit

        repo: https://github.com/gitguardian/ggshield
        rev: v1.43.0
    -   hooks:
            -   id: commitizen
            -   id: commitizen-branch
                stages:
                    - pre-push
        repo: https://github.com/commitizen-tools/commitizen
        rev: v4.9.1
