repos:
    -   repo: local
        hooks:
            -   id: branch-naming
                name: Branch naming convention check
                entry: .hooks/branch
                language: script
                stages:
                    - pre-commit
                always_run: true

    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
        hooks:
            -   id: check-ast
                language_version: python3.13
            -   id: trailing-whitespace
            -   id: end-of-file-fixer
            -   id: check-yaml
                exclude: ^k8s/
            -   id: check-toml

    -   repo: https://github.com/asottile/add-trailing-comma
    -   id: no-commit-to-branch
        args: [ "--branch", "main", "--branch", "master" ]

        rev: v3.2.0
        hooks:
            -   id: add-trailing-comma

    -   repo: https://github.com/asottile/pyupgrade
        rev: v3.20.0
        hooks:
            -   id: pyupgrade
                args:
                    - --py313-plus
    -   repo: local
        hooks:
            -   id: format
                name: format
                entry: uv run ruff format
                require_serial: true
                language: system
                types:
                    - python
    -   repo: local
        hooks:
            -   id: lint
                name: lint
                entry: uv run ruff check
                require_serial: true
                language: system
                types:
                    - python
                    -
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v1.18.2
        hooks:
            -   id: mypy

    -   repo: local
        hooks:
            -   id: pyright
                name: pyright
                entry: uv run basedpyright
                language: system
                types:
                    - python

    -   repo: https://github.com/gitguardian/ggshield
        rev: v1.43.0
        hooks:
            -   id: ggshield
                language_version: python3
                stages:
                    - pre-commit
