name: Code Formatting and Linting
permissions:
    contents: read

on:
    push:
        branches:
            - main
        paths:
            - "src/**"
            - "pyproject.toml"
            - "uv.lock"
            - "ruff.toml"
            - "pyrefly.toml"
    pull_request:
        paths:
            - "src/**"
            - "pyproject.toml"
            - "uv.lock"
            - "ruff.toml"
            - "pyrefly.toml"
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    formatting:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: [ "3.13" ]
        steps:
            -   name: Check out repository
                uses: actions/checkout@v5

            -   name: Install uv
                uses: astral-sh/setup-uv@v6
                with:
                    python-version: ${{ matrix.python-version }}
                    enable-cache: true

            -   name: Install dependencies
                run: uv sync --all-extras --group dev

            -   name: 🩺 Run linter
                run: uv run ruff check .

            -   name: Run formatter
                run: uv run ruff format .

            -   name: Type check
                run: uv run basedpyright .

            -   name: Run MyPy
                run: uv run mypy . --install-types --non-interactive
