name: Release

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            actions: write
            checks: write
            statuses: write
        env:
            dist_artifacts_name: dist
            dist_artifacts_dir: dist
            lock_file_artifact: uv.lock
        steps:
            -   name: Check out repository
                uses: actions/checkout@v5
                with:
                    ref: ${{ github.ref }}
                    token: ${{ secrets.GITHUB_TOKEN }}
                    fetch-depth: 0

            -   name: Configure Git user
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"

            -   name: Install uv
                uses: astral-sh/setup-uv@v5
                with:
                    pyproject-file: "pyproject.toml"
                    python-version: "3.13"
                    enable-cache: true
                    cache-dependency-glob: "**/pyproject.toml"

            -   name: Install dependencies
                run: uv sync --all-extras --group dev

            -   name: Build | Create Distribution Artifacts
                run: uv build

            -   name: Action | Semantic Version Release
                id: release
                uses: python-semantic-release/python-semantic-release@v10.4.1
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    git_committer_name: "github-actions"
                    git_committer_email: "actions@users.noreply.github.com"
                    changelog: true
                    build: false

            -   name: Publish | Upload to GitHub Release Assets
                uses: python-semantic-release/publish-action@v10.4.1
                if: steps.release.outputs.released == 'true'
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    tag: ${{ steps.release.outputs.tag }}

            -   name: Upload | Distribution Artifacts
                uses: actions/upload-artifact@v4
                with:
                    name: distribution-artifacts
                    path: dist
                    if-no-files-found: error
